language: node_js
node_js:
    - node
before_script:
    - yarn global add parcel-bundler --no-source-maps
script: parcel build index.html
after_script:
    - mv ./CNAME ./dist/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist/
  on:
    branch: master
