# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
import_types = ["diesel::sql_types::*", "diesel_geometry::sql_types::*"]
with_docs = true
