version: '3.3'
services:
    actix:
        env_file: ../.env
        environment:
            REDIS_URL: redis://redis
            DATABASE_URL: postgres://postgres
        build: .
        ports:
            - "5000:5000"
    redis:
        image: redis:latest
        volumes:
            - redis_data:/data
volumes:
    redis_data:

